### ISSUE TITLE
Spaces around text aren’t preserved

### ISSUE THREAD

**Issue by mathroc** [WebReflection/viperHTML#21]
```js
const viperHTML = require("viperhtml");

console.log(viperHTML.wire()`Hello ${"World"}`.toString()); // prints "HelloWorld"
```

by the way, is it intended to have to call `.toString()` ? it would be nice to add it to the readme if it is

it’s most likely caused by this line that changed recently : https://github.com/WebReflection/viperHTML/blob/c1f6455b81e6da62d82fe24d91fae84effc3be20/viperhtml.js#L310

so I can workaround it like this:

```js
const viperHTML = require("viperhtml");
viperHTML.adoptable = true;

console.log(viperHTML.wire()`Hello ${"World"}`.toString()); // prints "Hello <!--:1-->World<!--:1-->"
```

but it adds unnecessary comments, I only want the spaces, I’m not reusing it on the client

Also, I noticed something strange:

```js
const viperHTML = require("viperhtml");

viperHTML.wire()`Hello ${"World"}`;

viperHTML.adoptable = true;
console.log(viperHTML.wire()`Hello ${"World"}`.toString()); // prints "Hello<!--:1-->World<!--:1-->"
```

it adds the comments but trims the spaces !

**Comment by WebReflection** [comment]
> is it intended to have to call .toString() ?

only if you want to see the result because otherwise it's a buffer, not a string.

It looks like last changes introduced greedy trim. Mind if I ask *why* you want the spaces?

**Comment by WebReflection** [comment]
P.S. it's fixed
