### ISSUE TITLE
Non adoptable <textarea> / <style>

### ISSUE THREAD

**Issue by WebReflection** [WebReflection/viperHTML#22]
These two elements don't work well at all with adoptable layout.

It shouldn't really be a common case, and both works well without content, but adoptable should never put comments inside these elements when there is an interpolation.

Possible fix: when updates are created, somehow mark the one related to the interpolation inside textarea or style and do not put the comment in there

**Comment by joshgillies** [comment]
Would it be too much of a hack to use a data attribute as a way to mark adoptable content inside one of these elemebt types?

**Comment by WebReflection** [comment]
just to clarify:

  * hyperHTML adopt is not released so this bug is absolutely irrelevant right now for both projects (so time to get it right is crucial)
  * the issue is with template literals placeholders that gets wrapped. Moving placeholders from a template tag signature is a whole new world of mess I don't even want to think about
  * it's not trivial ... it's not by accident it's taking me ages to get adoptable content right :sob: 

thanks for the hint regardless

**Comment by joshgillies** [comment]
> Moving placeholders from a template tag signature is a whole new world of mess I don't even want to think about

Haha, of course!

**Comment by WebReflection** [comment]
As the adoption never landed, and as it's overly complicated and slow compared to solutions such as [heresy](https://github.com/WebReflection/heresy/#readme), I am closing this as won't fix.
