### ISSUE TITLE
viperHTML doesn’t close `<abbr>` elements

### ISSUE THREAD

**Issue by ExE-Boss** [WebReflection/viperHTML#27]
<code><a href="https://viperhtml.js.org/viper.html">viperHTML</a>\`prefix &lt;abbr&gt;anything&lt;/abbr&gt; postfix\`</code> returns `prefix <abbr>anything postfix` without the closing `</abbr>`, which causes `<abbr>` to span the rest of the node including ` postfix`, rather than just `anything`.

Testing the same with <code><a href="https://viperhtml.js.org/hyper.html">hyperHTML</a>\`prefix &lt;abbr&gt;anything&lt;/abbr&gt; postfix\`</code> correctly returns `prefix <abbr>anything</abbr> postfix`

**Comment by WebReflection** [comment]
that was a super rookie mistake from my side, apologies for that, it's fixed already.
