### ISSUE TITLE
Missing chunks/closing tags

### ISSUE THREAD

**Issue by laszbalo** [WebReflection/viperHTML#29]
I am working on my viperHTML webpack plugin and just came across a strange issue regarding to how viperHTML sanitzes/minifies the HTML, I have the following code:

```javascript
const {wire} = require("viperhtml")

console.log(wire()`<  h1   > ${'Bob'} </h1>`.toString())

// "<  h1   > Bob "
```

https://runkit.com/embed/v4yzhhcvk7g1

I was expecting to get back the sanitized/minified HTML, e.g.:
```javascript
// "<h1> Bob </h1>"
```
This is seems to be some error. What is your input on this?

**Comment by WebReflection** [comment]
My input is: write html
