### ISSUE TITLE
Render templates which are read as string from file.

### ISSUE THREAD

**Issue by dbauszus-glx** [WebReflection/viperHTML#31]
I can render my template with viperHTML from an implicit template literal.

```
  res.type('text/html').send(viperHTML.wire()`
  <!doctype html>
  <html lang="en">

  <head>
      <title>title</title>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  </head>

  <body>

  <div class="test">test</div>
          
  </body>

  </html>
  `);
```

How would I go along and turn a string read from the same html template file into a template literal for viperHTML?

```
  const _tmpl = fs.readFileSync(path.resolve(__dirname, '../public/views/hyper.html'), 'utf8');

  res.type('text/html').send(viperHTML.wire()`${_tmpl}`);
```

**Comment by WebReflection** [comment]
https://github.com/WebReflection/viperHTML#handy-patterns

**Comment by dbauszus-glx** [comment]
I did see this and made it work local. The problem though is that the application I am thinking about will be in the cloud using Zeit Micro to serve Http. The files will not be local but retrieved from GitHub via the GitHub API. Which means I cannot require the template. 😐

**Comment by dbauszus-glx** [comment]
I just mentioned filestream to keep it simple. Soz. Should have given more detail earlier.
