### ISSUE TITLE
Feature parity and partial attributes

### ISSUE THREAD

**Issue by WebReflection** [WebReflection/viperHTML#32]
Latest domtagger introduced partial attributes which are now available in both hyperHTML and lighterhtml.

Since viperHTML is designed to have feature parity with hyperHTML, find the time to implement this in this server side related project too.

**Comment by fernandocanizo** [comment]
Questions:

1. does heresy and heresy-ssr replace hyperhtml and viperhtml? I don't get what's the difference and hence, why not bringing whatever cool thing heresy has into hyper/viper.

2. I understand this lack of feature parity mean this is not true anymore: _"100% compatible with hyper(HTML) templates"_ (from the main page of viperhtml docs). I also don't get the differences between viper and hyper to raise the need to have two libraries. So my question is: is it too cumbersome to bring to viper the changes in hyper that avoid getting the issue #38 ? I guess is not a copy&paste, but maybe is something I can devote time to help compatibility between the two libraries be 100% again.

3. Is there any documentation for heresy(-ssr)?

**Comment by WebReflection** [comment]
Answers:

  1. heresy/heresy-ssr arrived 2 years later, so it's the other way around: anything that was good in viperHTML landed in there, plus much more, as heresy is all about defining custom elements in both client and server, with automatic hydration when served as SSR, so heresy-ssr will always be superior than viperHTML because the mechanism to hydrate can't be delivered in here

  2. viper is NodeJS, hyper is browser based. If you don't understand the difference between having a whole DOM environment on the browser and nothing on the server but libraries that are completely unnecessary on the client, I'm not sure how else to explain the difference. So, the reason there's no feature parity on attributes is that I need time to manipulate templates in a way that work well with 3rd parts libraries in charge of parsing the dom. I haven't found the time because heresy/ssr is superior, and also because having sparse attributes is YAGNI, not something crucial. True that I should update the 100% bit, as sparse attributes are not possible in viperHTML.

  3. there are various demos and examples and blog posts around, and all you need to know is how to define Custom Elements and how to use lighterhtml ... both have plenty of examples, heresy just put all the things together.

I am closing this as it's not really an issue, but feel free to ask me more if necessary 👋

**Comment by fernandocanizo** [comment]
First: thanks for taking the time to answer my basic questions. Probably this is not the place to discuss my concerns, but here we are now :)

Since the very first time I stumped with a post from you, you sell me the idea of simplify web development. So I decided on trying hyperhtml on my next project. The day came and I started looking around for docs again, so I found about viperhtml and everything else.

I understand that there are differences between the web (DOM and living stuff) versus server. However I don't get how those differences apply to a thing that started as a simple _tagged template string_, because that's the beginning of all this. After your answers I'm getting now that it's much more than a simple string interpolation, so much more that there're differences on the way it's implemented on a library for the web versus a library for the server.

So, when I found in #38 that interpolating some value in a string gives an error depending on the contents of the string, it was a big wtf-moment for me, cause it's totally unexpected behavior that the string part actually does something.

Anyway, now I'm going to replace hyperhtml with heresy and viperhtml with heresy-ssr as you say is the new thing with all the cool stuff. However you mention lighterhtml, and isn't clear to me if you just mentioned it as an example for using heresy, or if I will need lighterhtml with heresy.

Bonus question: won't it be the time to mark `/(hyper|viper|lighter?)html/` as deprecated?

From my experience trying to use your libraries I can tell you I found too much information about the _what_ and the _why_, but a lack of text telling about the **how**. I believe a good getting started guide, easily findable (maybe on the project's wiki?). I'd like to help with this if I manage to make all this work eventually.

**Comment by WebReflection** [comment]
> a thing that started as a simple tagged template string

**hyperHTML** has never been simple, it's actually one of the most complex Web stack I know, as it incorporates vDOM, polyfills, parsing, traversing, type handling, and much more, all through the tagged template DSL facade.

hyperHTML is indeed all about DX (Developer Experience) simplified to the extreme, a whole new level of simplification, when born in Mach 2017, impossible to obtain before template strings existed, as the main strength of templates is that they are *unique* per scope.

Strings interpolation also give simplicity to developers, but require strict rules when it comes to DOM applications, and all these libraries are about following these strict, but simple, rules, or everything fails (i.e. you can't have tag names interpolated)

**viperHTML** goal is to bring its client side cousin to the server, and it works pretty much the exact same, *except* for the sparse attributes, but the whole template string to actual HTML translation is different, and there are various third parts involved.

However, if you think you can put interpolations anywhere in a template literals, then you'll have issues with everything, including React and JSX, as there are rules to follow, and [these have been  documented](https://viperhtml.js.org/hyperhtml/documentation/) since day one.

**heresy** is a different beast, based on modern Web standards such as Custom Elements.

You can find [project goals and differences with viperHTML](https://github.com/WebReflection/heresy-ssr#project-goals) in the _heresy-ssr_ readme.

Heresy is based on **lighterhtml**, which works in both client and server, thanks to [basicHTML](https://github.com/WebReflection/basicHTML#readme), so any change that lands in _lighterhtml_, works out of the box in _heresy-ssr_.

That is not the case for _viperHTML_, 'cause it shares pretty much nothing with _hyperHTML_, while heresy shares 80% of the rendering logic with _lighterhtml_.

Where I work, we use _hyperHTML_ in production and we reach million of users through our extensions and its advanced settings page, it's been working extremely well and it's been compatible with any kind of browser, plus it's battle tested, but thanks to [HyperHTMLElement](https://github.com/WebReflection/hyperHTML-Element#readme) we just define Custom Elements through _hyperHTML_ and template literals, and it's been a game changer for the last 1.5 years.

However, since _hyperHTML_ is battle tested and shipped to millions, I've preferred to branch out [lighterhtml](https://github.com/WebReflection/lighterhtml#whats-different-from-hyperhtml-) as its successor, and truth to be told I might as well get rid of _hyperHTML_ these days, except it has a super handy feature: [intents](https://viperhtml.js.org/hyperhtml/documentation/#api-3).

Defining intents became the easiest way for us to provide internationalization through `data-i18n` attributes, and that feature alone has been another game-changer.

_lighterhtml_, on the other hand, is smaller, and more suitable for integration with third parts libraries, including _heresy_, [neverland](https://github.com/WebReflection/neverland/#readme), [wickedElements](https://github.com/WebReflection/wicked-elements#readme), [hookedElements](https://github.com/WebReflection/hooked-elements#readme), and literally any library that would like to use template literals to define, and update at speed light, DOM nodes.

If you were following me on medium, [you would've known all this already](https://medium.com/@WebReflection/about-my-web-libraries-9b1e179d134), which also means that ...

> won't it be the time to mark /(hyper|viper|lighter?)html/ as deprecated?

this is absolutely not the time to deprecate any of these libraries, as all of them are super actively used, developed, maintained, or shipped to millions.

The only exception here is _viperHTML_ that never gained too much traction, which is also the reason I've created heresy, recently featured [in this context too](https://webcomponents.dev/blog/all-the-ways-to-make-a-web-component/) (spoiler: it's doing great!).

Enough with the history of my libraries though, but if you follow me on twitter and medium, you'll find tons of examples or [articles](https://medium.com/@WebReflection/heresy-mappedattributes-fragment-and-define-less-components-28ae4a20e8c3) on how to do this or that.

Yes, that's not the equivalent of a proper documentation about everything, but as you can see, I actively maintain dozen projects, if not hundreds, and time is a big constrain, so that less popular stuff gets behind and once again, not having sparse attributes, as these have never been possible up to few months ago anyway, is everything but crucial for me to solve in _viperHTML_.

But of course, pull requests are welcome.

**Comment by fernandocanizo** [comment]
Thank you very much indeed Andrea. This post clarifies several doubts I had. Thanks for taking the time to answer me.

I follow you on Twitter and Medium already, however I'm not an active "news" reader, so I've missed some (probably many) of your posts.

Keep up the good work. :)

**Comment by WebReflection** [comment]
@fernandocanizo just in case the previous explanation wasn't detailed enough, I've summarized all the libraries and combos I have in this gist: https://gist.github.com/WebReflection/761052d6dae7c8207d2fcba7cdede295 👋
