### ISSUE TITLE
Website with REPL?

### ISSUE THREAD

**Issue by flagello** [WebReflection/viperHTML#4]
Would you be interested in putting up a website (say [viperhtml.js.org](https://viperhtml.js.org)) with a minimal REPL with examples [a là Svelte](https://svelte.technology/repl)?

- Key details (as in the hyperHTML's readme)
- REPL
- Links

**Comment by WebReflection** [comment]
absolutely, I just don't have the time for it right now.

I will try to find some time around June

**Comment by WebReflection** [comment]
Closing this, as something I know I absolutely need to do, also for hyperHTML and others.

My current mission is summarized in here:
https://viperhtml.js.org/
