### ISSUE TITLE
updates[(i - 1)] is not a function

### ISSUE THREAD

**Issue by jscari** [WebReflection/viperHTML#9]
Hi,

I have a `myFunction`function declared inside my HTML

```
var a = { text: 'A' };
var render = viperHTML.wire();
var result = render`
<script> function myFunction() { alert('hello'); }</script>
<button onclick="myFunction()" >${a.text}</button>
`;
console.log(result.toString());
```

Giving me this output:

```
<script>function myFunction(){alert("hello")}</script>
<button onclick="myFunction()">A</button>
```

This is fine, but, now I want to send a parameter

```
var result = render`
<script> function myFunction(text) { alert('hello'); }</script>
<button onclick="myFunction('${a.text}')" >${a.text}</button>
`;
```

and I get the following error

> TypeError: updates[(i - 1)] is not a function

and I can't declare the event as in the basic exemple

`var a = { ..., onclick: (e) => e.preventDefault() };`

I guess, I'm trying to mix different things here, but is it possible ? Could you point me please to the correct syntax I should use ?

note: I'm using this workaroud now

```
<script> function myFunction(e) { alert(e.getAttribute('data-x')); }</script>
<button onclick="myFunction(this)" data-x="${a.text}">${a.text}</button>
```

Thanks

**Comment by WebReflection** [comment]
There is no support for partial attributes. You cannot do this: `<button onclick="myFunction('${a.text}')" >${a.text}</button>`

What you can do hoever, is the following:
```js
var result = render`
<button onclick="${e => alert(this.textContent)}">${a.text}</button>`;
```

Unless you need the same function on the client side, there's no way you can have client side behavior in NodeJS but viperHTML can put the right callback as listener.

Just don't ever put interpolation as attribute content, it won't ever possibly work.

**Comment by jscari** [comment]
Got it. thanks
